### ISSUE TITLE
i can't get comments datas

### ISSUE THREAD

**Issue by cced3000** [valga/instagram-rest-api#1]
`<?php 
$mediaId='1536250261863951712';
$comments = $apiClient->comments->get($mediaId)->getData();
print_r($comments);`

Fatal error: Uncaught InvalidArgumentException: "1536250261863951712" is not a valid media identifier. in D:\phpStudy\WWW\img\vendor\valga\instagram-rest-api\src\Endpoint.php:62 Stack trace: #0 D:\phpStudy\WWW\img\vendor\valga\instagram-rest-api\src\Endpoint\Comments.php(52): InstagramRestApi\Endpoint->filterMediaId('153625026186395...') #1 D:\phpStudy\WWW\img\examples\userMedia.php(13): InstagramRestApi\Endpoint\Comments->get('153625026186395...') #2 {main} thrown in D:\phpStudy\WWW\img\vendor\valga\instagram-rest-api\src\Endpoint.php on line 62

**Comment by valga** [comment]
Valid media identifier looks like this one: `823251211150230726_25025320`. Second number is media owner's account ID.

**Comment by valga** [comment]
So, in your case it is `1536250261863951712_222356238`.
